Use the plone.app.multilingual conditionally
plone/plone.volto pull request #120
Opened 2023-05-18 20:52 UTC by folix-01

2023-05-18 20:52 UTC, mister-roboto commented
@folix-01 thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2023-05-22 21:23 UTC, mauritsvanrees requested changes
The changes are good, but I would want one extra.  There should be a `zcml:condition="installed plone.app.multilingual"` in `profiles.zcml` in the `multilingual` profile.

2023-07-12 14:25 UTC, jensens approved these changes

2023-07-12 14:26 UTC, merged

2023-07-13 15:12 UTC, mauritsvanrees commented on src/plone/volto/profiles.zcml
> +    xmlns:zcml="http://namespaces.zope.org/i18n"
This works???  It should be `/zcml` at the end of this line.

Fixed directly on main in commit 8358b85b2f3e46bb8d603a78d2e77be049628d66.