Add VOLTO_FRONTEND_DOMAIN as env var
plone/plone.volto pull request #139
Opened 2024-01-22 13:11 UTC by sneridagh

2024-01-22 13:11 UTC, mister-roboto commented
@sneridagh thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-01-23 17:39 UTC, davisagli requested changes

2024-01-23 17:39 UTC, davisagli commented on src/plone/volto/patches.py
> +        settings_frontend_domain = os.environ["VOLTO_FRONTEND_DOMAIN"] or getattr(
We don't want to require it.

```suggestion
        settings_frontend_domain = os.environ.get("VOLTO_FRONTEND_DOMAIN") or getattr(
```

2024-01-29 17:07 UTC, davisagli approved these changes

2024-01-29 17:08 UTC, davisagli commented
@jenkins-plone-org please run jobs

2024-01-30 18:00 UTC, merged

2024-02-01 03:04 UTC, djay commented
@sneridagh for multitenented mode we are going to need another solution for this (and also some other settings). It would be good to know what the preferred solution is for that